# Generated by Django 4.1.5 on 2023-04-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative_Eigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNumber', models.IntegerField()),
                ('fieldName', models.CharField(max_length=30)),
                ('fieldChoice', models.IntegerField()),
                ('notknown', models.IntegerField(null=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alternative_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNumber', models.CharField(max_length=50)),
                ('fieldChoice', models.CharField(max_length=50, null=True)),
                ('alternativeChoice', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldChoice', models.CharField(max_length=50)),
                ('alternativeChoice', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Criteria_Table_Eigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=30)),
                ('fieldChoice', models.IntegerField()),
                ('value', models.IntegerField()),
                ('notknown', models.IntegerField(null=True)),
            ],
        ),
    ]
